### PR TITLE
Bank business card changes to return preformated URL

### PR DESCRIPTION
**Pull request by jsilhan**

### CODE REVIEW

**Comment by jsilhan** [comment]
@MPdevelopers @zzuzzy @rubickcz @matllubos pls review

**Comment by jsilhan** [comment]
@MPdevelopers @zzuzzy @rubickcz @matllubos pls review

**Comment by MPdevelopers** [comment]
Conflict. JInak ~OK.

**Comment by jsilhan** [comment]
@MPdevelopers rebasnuto

**Pull request merged**
